### ISSUE TITLE
Publishing updated versions to crates.io

### ISSUE THREAD

**Issue by 0xOmarA** [GREsau/okapi#126]
Looking at `rocket_okapi` in [crates.io](https://crates.io/crates/rocket_okapi) it seems like the last version that was published there was 0.5.1. 

Is the team planning on releasing v0.7.0 to crates.io? I would like to use this crate in something that I'm building and would ideally like to depend on it through crates.io instead of github.

**Comment by ralpha** [comment]
A new version was releases about a month ago: v0.8.0-rc.3
https://crates.io/crates/rocket_okapi/versions
These are pre-release versions because Rocket is currently also releasing release candidates.
Once they release a more a new version we will do the same.

The last released version of `okapi` reflects the current state of this GitHub repo.

**Comment by ralpha** [comment]
As Rocket now has a stable release, the next version will be stable again.
Will close, next version should be out soon-ish :crossed_fingers:
