### ISSUE TITLE
When 0.8 release

### ISSUE THREAD

**Issue by sunliang711** [GREsau/okapi#135]
Hello, I want to use  v0.8 of okapi because I'm using rocket v0.5, so  when will you release v0.8

**Comment by TotalKrill** [comment]
Just a pro tip, It's usually more polite to ask if there is anything you can help with to have a 0.8 release. This is volunteer work after all :)

**Comment by sunliang711** [comment]
> Just a pro tip, It's usually more polite to ask if there is anything you can help with to have a 0.8 release. This is volunteer work after all :)

Thank you for the guidance! I appreciate the reminder about being proactive. Is there anything specific you would like assistance with or any particular area you think needs extra attention for the 0.8 release? I'm more than happy to contribute and ensure we have a successful release.

**Comment by ralpha** [comment]
Haha, I can take direct questions. :smile:  But yes, want to finish it, but don't have a lot of time, so do it after work where possible.

I still have some open local changes and some small notes for things I have to check.
But most of them require some more in depth knowledge or are quite difficult to figure out.

But this might be one that you can help with:
Can we implement `OpenApiResponderInner` for: https://api.rocket.rs/v0.5/rocket_ws/stream/struct.MessageStream.html
Because it implements [`Responder`](https://api.rocket.rs/v0.5/rocket/response/responder/trait.Responder.html)
Example on how to implement can be found here. [rocket-okapi/src/response/responder_impls.rs](https://github.com/GREsau/okapi/blob/master/rocket-okapi/src/response/responder_impls.rs)
Because it is generated using a macro the type might not be known at compile time. But if it can be, then we need to implement that.

Other then that look though the issues and see if you can fix any of them, or just provide more info.

Also you can just test the current code base and see if everything is working.
Something like this can be used.
```toml
rocket_okapi = { git = "https://github.com/GREsau/okapi.git", features = ["swagger", "rapidoc"] }
```
Then I know that at least it is working for people before I release it.

**Comment by ralpha** [comment]
I just implemented the above stated addition.
Most of changes I want for the next release are added, just some smaller updates/fixes left.

So if no blockers it will not be long before the next release.

**Comment by ralpha** [comment]
The new versions of all 3 crates have been published:
- okapi v0.7.0: https://crates.io/crates/okapi/0.7.0
- rocket_okapi v0.8.0: https://crates.io/crates/rocket_okapi/0.8.0
- rocket_okapi_codegen v0.8.0: https://crates.io/crates/rocket_okapi_codegen/0.8.0
