### ISSUE TITLE
Route description

### ISSUE THREAD

**Issue by TatriX** [GREsau/okapi#3]
It seems that route docs doesn't currently used to generate route descriptions.
Am I missing anything?

Thanks for the project!

**Comment by GREsau** [comment]
That behaviour isn't currently implemented, but it's a good idea - I'll definitely keep it in mind for future enhancements

**Comment by leeola** [comment]
I'm not familiar with Proc Macros at all, but I wrote up a POC here: https://github.com/GREsau/okapi/compare/master...leeola:fn-doc-support _(because I too needed the feature)_.

That branch generates both a description and the summary from the docstring on a rocket route.

@GREsau Let me know if you'd like me to make a PR. There are a couple FIXME's. Note that I'm not immediately making the PR because it was a hastily, uninformed POC and there may be _much_ better ways to implement it. Nevertheless, I figured I'd link my attempt in case it helps anyone.

**Comment by GREsau** [comment]
Sorry for the slow turnaround, I've just started looking at this.

I'm planning on copying [schemars's behaviour](https://graham.cool/schemars/examples/6-doc_comments/), so if the first line of the doc comment begins with a # (i.e. if it's a markdown heading), then it will be used as the title (or summary in this case). The rest of the doc comment will be used as the description.
