### ISSUE TITLE
Warning for feature(specialization)

### ISSUE THREAD

**Issue by ralpha** [GREsau/okapi#32]
With the new nightly compiler I get the following warning.
```
warning: the feature `specialization` is incomplete and may not be safe to use and/or cause compiler crashes
 --> rocket_okapi/src/lib.rs:1:12
  |
1 | #![feature(specialization)]
  |            ^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #31844 <https://github.com/rust-lang/rust/issues/31844> for more information
```
Referring to this line:
https://github.com/GREsau/okapi/blob/86da308e1d6b3511aee0f043be9f983d4ea242fe/rocket-okapi/src/lib.rs#L1

I have not looked into this much and everything seems to work fine, but just so you know.

**Comment by ralpha** [comment]
If anyone want to suppress the warning use:
```rust
#![allow(incomplete_features)]
#![feature(specialization)]
```

**Comment by GREsau** [comment]
Specialization is currently used both in rocket and rocket-okapi for the same reason - to make `Result<T,E>`'s implementation of `Responder` behave differently depending on whether `E` implements `Responder`.

This behaviour has been removed in rocket 0.5, but while we're supporting rocket 0.4 there's no easy way to remove specialization  (and no discernible benefit, since you'll still need specialization enabled for rocket).
