### ISSUE TITLE
Cannot use rocket::response::stream::EventStream with okapi

### ISSUE THREAD

**Issue by g-murzik** [GREsau/okapi#52]
Hi,

First of all thanks for contributing `okapi` to the world!

I just tried to use the first [EventStream example from the Rocket documentation](https://api.rocket.rs/v0.5-rc/rocket/response/stream/struct.EventStream.html#examples) decorated with `#[openapi]` and ran into the following error:

```
cargo build
   Compiling example v0.1.0 (...)
error[E0562]: `impl Trait` not allowed outside of function and inherent method return types
  --> src/main.rs:54:16
   |
54 | fn stream() -> EventStream![] {
   |                ^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

It compiles just fine when I use `#[openapi(skip)]` instead of `#[openapi]`. But do you have any idea how to make the example work with `#[openapi]`? Any help would be highly appreciated!

**Comment by ralpha** [comment]
The `EventStream` is new in Rocket 0.5.0 (I think). And I don't think this has been added yet (or even looked at).
So you are just breaking new ground at the moment. :)
I would have to look into this to know what the problem is (don't have much time at the moment), wrapping up some other projects atm.
But my best guess is that the macro syntax in that line is triggering something in the codegen of the code.
For now I think your best bet is to try and see if you can replace the `EventStream![]` with something.
But I don't know if this is even possible.
Maybe something along the lines of:
```rust
type EventStreamResponse = EventStream![];
#[get("/events")]
#[openapi]
fn events() -> EventStreamResponse {
    // ...
}
```
I don't know if this will work, but may be worth a try.

I'll leave this ticket open so we can properly fix this later.

**Comment by lrodriguez14** [comment]
Hello @ralpha,

Any updates about this?

Thanks!
