### ISSUE TITLE
Specific error handling

### ISSUE THREAD

**Issue by Joseda8** [GREsau/okapi#79]
Following the **Custom Schema** example I saw the errors are defined by doing in the `error.rs` file:

```
        responses.insert(
            "400".to_string(),
            RefOr::Object(OpenApiReponse {
                description: "Description".to_string(),
                ..Default::default()
            }),
        );
```

I would like to know. Is it possible to show this error in some few endpoints only? Currently this code is adding this error to all endpoints in Swagger.

**Comment by ralpha** [comment]
Yes, see my reply here: https://github.com/GREsau/okapi/issues/77#issuecomment-1065537644

Short is: create multiple error structs or use one of the methods described here: https://github.com/GREsau/okapi/issues/34#issuecomment-1040365947

I'll close this issue because of duplicates to #34 and #77.
If you have more questions, just ask.
