### ISSUE TITLE
How to implement JsonSchema trait for extern structs?

### ISSUE THREAD

**Issue by sebboer** [GREsau/okapi#81]
How can I implement the JsonSchema trait for an external struct? My endpoint returns an external struct that implements Serialize. But for this I can't run the derive macro for JsonSchema. I managed it with a wrapper struct and a manual implementation but it is very cumbersome. Is there a simpler approach to this?

```rust
// extern crate
#[derive(Clone, Debug, Default, Deserialize, Serialize)]
struct Bar {
  id: i32,
  name: String,
}

//////

struct BarWrapper(Bar);

impl JsonSchema for BarWrapper {
    fn schema_name() -> String {
        "Bar".to_string()
    }

    fn json_schema(gen: &mut SchemaGenerator) -> Schema {
        let price = Bar {
          id: 123,
          name: "Bar".to_string(),
        };
        let schema = schema_for_value!(price);
        let mut schema_object = schema.schema;
        schema_object.metadata().description = Some("bar model".to_string());
        schema_object.into()
    }
}

#[openapi]
#[get("/")]
fn get_bar() -> Json<Bar> {
    let bar = Bar::default();
    Json(BarWrapper(bar))
}
```

**Comment by ralpha** [comment]
This is more a `Schemars` question, but I'll answer it here. 

Because of current limitations in Rust you can only implement traits for structs in 2 places:
- Original crate where structs is created.
- Crate where trait is created (`Schemars` in this case)

So depending on the crate it changes a bit, but your best bet is to ask the original crate owners or `Bar` to impl `JsonSchema`.
Or use the wrap like you currently have. (this is sometimes the easiest way to do it without relaying on others.)

Other info: https://github.com/GREsau/schemars/issues/131
