### ISSUE TITLE
update basic example

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [GREsau/okapi#83]
I tried the copy paste example as provided here: https://docs.rs/rocket_okapi/latest/rocket_okapi/#example and got a
```
[Running 'cargo run']
    Blocking waiting for file lock on package cache
    Updating crates.io index
error: failed to select a version for the requirement `okapi = "^0.5.1"`
candidate versions found which didn't match: 0.4.0, 0.3.0, 0.2.0, ...
location searched: crates.io index
```

Which versions should I use?

**Comment by HerrMuellerluedenscheid** [comment]
This seems to be a working configuration:
```
[dependencies]
rocket = "0.4.10"
rocket_okapi = "0.5"
schemars = "0.7"
okapi = { version = "0.4.0", features = ["derive_json_schema"] }
serde = "1.0.136"

[dependencies.rocket_contrib]
version = "0.4.10"
default-features = false
features = ["json"]
```

The examples at https://docs.rs/rocket_okapi/latest/rocket_okapi/#example should probably be updated accordingly.

**Comment by HerrMuellerluedenscheid** [comment]
I was wrong. `rocket > 0.5` is required. So, what should a working dependency setup look like?

**Comment by ralpha** [comment]
Hello @HerrMuellerluedenscheid Thanks for the message.
I would like to note that the 'latest' version is not the version we are currently working on (so not actually the latest).
There has been quite a few beta/release candidates since then. This is because these use the Rocket release candidate.
Okapi versions: https://crates.io/crates/okapi/versions
Rocket_okapi versions: https://crates.io/crates/rocket_okapi/versions

A lot of things has changed since then.
So I would highly recommend using version `0.8.0-rc.1` and use Rocket version `0.5.0-rc.1`.
Both version are very stable and have been using both for quite a while.

I know this is confusing but this is because we are waiting for a new release of Rocket. And there where some delays there.
Hope there will be progress there.
Using the examples from the `master` branch on GitHub well be best to get the latest version running.
They should al work as expected.
https://github.com/GREsau/okapi/tree/master/examples
The [json-web-api](https://github.com/GREsau/okapi/blob/master/examples/json-web-api/src/main.rs) is a very basic example.
The [Custom Schema](https://github.com/GREsau/okapi/tree/master/examples/custom_schema) might be the layout for a the start of an actual application. This is also similar to how I use the code in my projects. (maybe I should change the name for this example)

If you still think the example could use some improvement, please let me know how to improve them.
And if you have other questions, let me know.

**Comment by ralpha** [comment]
Just noted that some examples still try to use `v0.8.0-alpha-1` which was renamed to `v0.8.0-rc.1`
https://github.com/GREsau/okapi/blob/e686b442d6d7bb30913edf1bae900d14ea754cb1/examples/custom_schema/Cargo.toml#L9
So that might need to be changed if you try using them. (and remove the `path = "../../rocket-okapi",` too, so it will get the version from crates.io)
Will try to fix that soon.

**Comment by HerrMuellerluedenscheid** [comment]
Dear @ralpha,

Thanks for the explanation and for the hint regarding the examples. I based my project on these. If possible I think it would be a good idea to replace the example on crates.io with a link to the examples directory. That would also mean that no duplicate maintenance of examples and documentaiton is required. And it would lead to less confusion.

Anyways, okapi is an awesome project it's fun to use!

Best
Marius

**Comment by ralpha** [comment]
Thanks :smiley: 
I can not update the description of previous versions, but will add some links to the new readme.
586978f2e8806f4cb1be2ca70a6abb56b3202ec9
