### ISSUE TITLE
Version dependecy to crate "rocket"

### ISSUE THREAD

**Issue by heikki-heikkila** [GREsau/okapi#93]
There seems to be a bug in Cargo.toml for okapi package, 0.8.0-rc.1.  Note these dependencies:

[dependencies.rocket]
version = "0.5.0-rc.1"
. . omitted text

[dependencies.rocket_okapi_codegen]
version = "=0.8.0-rc.1"

So this crate requires **exactly** version 0.8.0-rc.1 of rocket_okapi_codegen but for "rocket", the requirement is **less** specific, "0.5.0-rc.1".

I tried to build a HTTP server with rocket_okapi 0.8.0-rc.1.  For some reason, cargo chose to download version 0.5.0-rc.2 of rocket from crates.io (although my own Cargo.toml asked for 0.5.0-rc.1).  Then rocket_okapi didn't compile; as stated in changelog of rocket, versions 0.5.0-rc.1 and 0.5.0-rc.2 are not compatible; so there's a **reason** why okapi asks for 0.5.0-rc.1.

But is the version request "0.5.0-rc.1" specific enough?  Perhaps it would fix the issue if the requirement for rocket were made exact, "=0.5.0-rc.1".

**Comment by ralpha** [comment]
This should be fixed now (in master) because of updates needed for #88.
I fixed the version for future `rc` versions of Rocket. See commit: 901461bd5ef5ad8ecfc2990e8e6979c6f6c77272
If you want to keep using Rocket `0.5.0-rc.1` you can use the branch [`rocket-0.5.0-rc.1`](https://github.com/GREsau/okapi/tree/rocket-0.5.0-rc.1)
